baseURL = 'https://suiend.netlify.app/'
languageCode = 'en-us'
title = 'SUIEND'
theme = "PaperMod"


[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"




  [[menu.main]]
  name = "Bluesky.social"
  url = "https://bsky.app/profile/havexit.bsky.social"
  weight = 30

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
