baseURL = 'https://suiend.netlify.app/'
languageCode = 'en-us'
title = 'SUIEND'
theme = "PaperMod"






  [[menu.main]]
  name = "Bluesky.social"
  url = "https://bsky.app/profile/havexit.bsky.social"
  weight = 30
