baseURL = 'https://suiend.netlify.app/'
languageCode = 'en-us'
title = 'F451'
theme = "PaperMod"


[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"

taxonomies = { tag = "tags", category = "categories" }



  [[menu.main]]
  name = "Fedibird"
  url = "https://bsky.app/profile/havexit.bsky.social"
  weight = 30

  [[menu.main]]
  name = "Wavebox"
  url = "https://bsky.app/profile/havexit.bsky.social"
  weight = 30

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
